### ISSUE TITLE
Gandhi email server

### ISSUE THREAD

**Issue by ckarsten1** [Gandi/gandi-vm-config#29]

**Comment by Themimitoof** [comment]
Hello @ckarsten1,

This repository is not related in any means about Gandi's email servers. If you have any questions about our email services, please take a look to [our documentation](https://docs.gandi.net/en/gandimail/index.html) or [contact our support team](https://helpdesk.gandi.net/hc/en-us). 

In any case, since this ticket is missing context and is not related to the content of this repository, I'm gonna labeling it as invalid and close it. If you think I'm wrong, please, feel free to re-open the issue and give us more context by updating the description of the issue.

Have a nice day!
